name: shelf_cors
version: 0.1.0
author: George Moschovitis <george.moschovitis@gmail.com>
description: Middleware to add CORS headers to shelf responses.
dependencies:
  shelf: any
dev_dependencies:
  unittest: any
